---
name: ducati-guardian

# replace with bosh status --uuid
director_uuid: <%= `bosh target lite > /dev/null 2>&1 && bosh status --uuid` %>

releases:
  - name: guardian
    version: latest
  - name: ducati
    version: latest

networks:
  - name: garden
    subnets:
      - range: 10.244.16.0/24
        reserved: [10.244.16.1]
        static: &garden_addresses
          - &test_address_1 10.244.16.2
          - &test_address_2 10.244.16.3
          - &db_address 10.244.16.9

        cloud_properties:
          name: random

jobs:
  - name: acceptance-tests
    lifecycle: errand
    instances: 1
    templates:
      - name: acceptance-tests
        release: ducati
    resource_pool: garden
    networks:
      - name: garden
    properties:
      ducati:
        acceptance_tests:
          garden_server_1: *test_address_1
          garden_server_2: *test_address_2

  - name: garden
    instances: 2
    templates:
      - name: garden
        release: guardian
      - name: ducati
        release: ducati
    resource_pool: garden
    networks:
      - name: garden
        static_ips: [ *test_address_1, *test_address_2 ]
    properties:
      ducati:
        daemon:
          database:
            host: *db_address
            username: postgres
            password: ""
            name: ducati
            ssl_mode: disable
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        network_plugin: /var/vcap/packages/ducati/bin/guardian-cni-adapter
        network_plugin_extra_args:
          - "--cniPluginDir=/var/vcap/packages/ducati/bin"
          - "--cniConfigDir=/var/vcap/jobs/ducati/cni-conf"
          - "--ducatiSandboxDir=/var/vcap/data/ducati-sandbox"
          - "--daemonBaseURL=http://localhost:4001"
          - "--nsBindMountRoot=/var/vcap/data/ducati/bind-mounts"
          - "--logDir=/var/vcap/sys/log/ducati/adapter"

resource_pools:
  - name: garden
    network: garden
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      name: random

compilation:
  workers: 3
  network: garden
  cloud_properties:
    name: random

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
