---
etcd_static_ips: &etcd_static_ips
- 10.244.15.6

name: ducati-guardian

# replace with bosh status --uuid
director_uuid: <%= `bosh target lite > /dev/null 2>&1 && bosh status --uuid` %>

releases:
  - name: guardian
    version: latest
  - name: ducati
    version: latest
  - name: etcd
    version: latest

jobs:
  - name: garden
    instances: 2
    templates:
      - name: garden
        release: guardian
      - name: ducati
        release: ducati
    resource_pool: garden
    networks:
      - name: garden
    properties:
      ducatid:
        etcd_machines: *etcd_static_ips
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        network_plugin: /var/vcap/packages/cni-plugins/bin/guardian-cni-adapter
        network_plugin_extra_args: "--cniPluginDir=/var/vcap/packages/cni-plugins/bin,--cniConfigDir=/var/vcap/jobs/ducati/cni-conf,--ducatiSandboxDir=/var/vcap/data/ducati-sandbox,--daemonBaseURL=http://localhost:4001"
  - name: etcd
    instances: 1
    templates:
      - name: etcd
        release: etcd
    resource_pool: garden
    networks:
      - name: etcd
        static_ips: *etcd_static_ips
    properties:
      etcd:
        machines: *etcd_static_ips
        cluster:
          - name: etcd
            instance: 1
        peer_require_ssl: false
        require_ssl: false

networks:
  - name: garden
    subnets:
      - range: 10.244.16.0/24
        reserved: [10.244.16.1]
        static: [10.244.16.6]
        cloud_properties:
          name: random
  - name: etcd
    subnets:
      - range: 10.244.15.0/24
        reserved: [10.244.15.1]
        static: *etcd_static_ips
        cloud_properties:
          name: random

resource_pools:
  - name: garden
    network: garden
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      name: random

compilation:
  workers: 3
  network: garden
  cloud_properties:
    name: random

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
