---
name: ducati-guardian

# replace with bosh status --uuid
director_uuid: <%= `bosh target lite > /dev/null 2>&1 && bosh status --uuid` %>

releases:
  - name: guardian
    version: latest
  - name: ducati
    version: latest

jobs:
  - name: garden
    instances: 1
    templates:
      - name: garden
        release: guardian
      - name: ducati
        release: ducati
    resource_pool: garden
    networks:
      - name: garden
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

networks:
  - name: garden
    subnets:
      - range: 10.244.16.0/24
        reserved: [10.244.16.1]
        static: [10.244.16.6]
        cloud_properties:
          name: random

resource_pools:
  - name: garden
    network: garden
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      name: random

compilation:
  workers: 3
  network: garden
  cloud_properties:
    name: random

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
