#!/bin/bash -eu

# works like
#     ip netns exec $NAMESPACE $CMD $ARGS...
# but $NAMESPACE is an arbitrary relative or absolute path

target=$(readlink -f "$1")
shift

linkname=$(cat /dev/urandom | base64 | tr -d '+/' | head -c 8)
linkpath=/var/run/netns/$linkname

ln -s "$target" "$linkpath"

set +e
ip netns exec $linkname "$@"
exitcode=$?
set -e

rm "$linkpath"

exit $exitcode
