#!/bin/bash
set -e -u

ROOT_DIR_PATH=$(cd $(dirname $0)/.. && pwd)
cd $ROOT_DIR_PATH

docker run --privileged \
   --rm \
   -v $PWD:/ducati-release \
   -e GOPATH=/ducati-release \
   -e GINKGO_EXTRA_FLAGS="${GINKGO_EXTRA_FLAGS:-""}" \
   -e NO_POSTGRES="${NO_POSTGRES:-""}" \
   -w / \
   c2cnetworking/ducati-dev \
   /ducati-release/ci/ducati-tests.sh "$@"
