#!/bin/bash
set -e -x

ROOT_DIR_PATH=$(cd $(dirname $0)/.. && pwd)
cd $ROOT_DIR_PATH

docker run --privileged \
   --rm \
   -v $PWD:/ducati-release \
   -e GOPATH=/ducati-release \
   -w / \
   c2cnetworking/ducati-dev \
   /ducati-release/ci/ducati-tests.sh "$@"
