#!/bin/bash
set -e

ROOT_DIR_PATH=$(cd $(dirname $0)/.. && pwd)
cd $ROOT_DIR_PATH

if [ -z $FLYTO ]; then
  fly execute -x -p -c ci/ducati-tests.yml -i ducati-release=.
else
  fly -t $FLYTO execute -x -p -c ci/ducati-tests.yml -i ducati-release=.
fi
